from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)
from reportlab.lib import colors
from reportlab.lib.units import inch


def create_pdf(summary, explanations, risks, entities, ambiguities, sentiment):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(name='Title', fontSize=18, fontName='Helvetica-Bold', textColor=colors.darkblue)
    normal_style = styles['Normal']
    story = [
        Paragraph("Contract Analysis Report", title_style),
        Spacer(1, 12),
        Paragraph("Generated by Contract Analysis Tool", styles['Italic']),
        Spacer(1, 12),
        Paragraph(summary.replace("\n", "<br/>"), normal_style),
        Spacer(1, 12),
        Paragraph("Key Entities", styles['Heading2']),
        Table([
            ["Parties", ', '.join(entities['Parties']) or 'N/A'],
            ["Dates", ', '.join(entities['Dates']) or 'N/A'],
            ["Amounts", ', '.join(entities['Amounts']) or 'N/A'],
            ["Jurisdiction", ', '.join(entities['Jurisdiction']) or 'N/A']
        ], colWidths=[2*inch, 4*inch]),
        Spacer(1, 12),
        Paragraph("Risk Analysis", styles['Heading2']),
        Table([
            [k, ', '.join(v) if v else 'None'] for k, v in risks.items()
        ], colWidths=[2*inch, 4*inch], style=TableStyle([('BACKGROUND', (0,0), (-1,0), colors.grey), ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke)])),
        Spacer(1, 12),
        Paragraph("Ambiguities", styles['Heading2']),
        Paragraph(', '.join(ambiguities) or 'None detected', normal_style),
        PageBreak(),
        Paragraph("Clause Explanations", styles['Heading2']),
    ]
    for exp in explanations:
        story.append(Paragraph(exp, normal_style))
        story.append(Spacer(1, 8))
    doc.build(story)
    buffer.seek(0)
    return buffer